### model
model_name_or_path: /gemini/data-2/Customization-7Bs-merge/llama2-7B/whitebox/llama2-7B-medmcqa-whitebox

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05

### ddp
ddp_timeout: 180000000
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: medmcqaInstruct
template: llama2
cutoff_len: 512
max_samples: 100000000
overwrite_cache: false
preprocessing_num_workers: 8

### output /gemini/data-2/mix-ckpt-70b/cust/math
output_dir: /gemini/data-2/Customization-7Bs/Llama2-lora/whitebox/llama2-7B-medmcqa-whitebox-3epoch
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
report_to: wandb
run_name: Llama2-7B-medmcqa-Cust-lora-whitebox # 可选

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true

### eval
val_size: 0.08
per_device_eval_batch_size: 32
eval_strategy: steps
eval_steps: 1000
