### model
model_name_or_path: /gemini/data-2/mistral-7B


### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: layers.0.self_attn.q_proj,layers.0.self_attn.k_proj,layers.0.self_attn.v_proj,layers.0.self_attn.o_proj,layers.0.mlp.gate_proj,layers.0.mlp.up_proj,layers.0.mlp.down_proj,layers.1.self_attn.q_proj,layers.1.self_attn.k_proj,layers.1.self_attn.v_proj,layers.1.self_attn.o_proj,layers.1.mlp.gate_proj,layers.1.mlp.up_proj,layers.1.mlp.down_proj,layers.2.self_attn.q_proj,layers.2.self_attn.k_proj,layers.2.self_attn.v_proj,layers.2.self_attn.o_proj,layers.2.mlp.gate_proj,layers.2.mlp.up_proj,layers.2.mlp.down_proj,layers.3.self_attn.q_proj,layers.3.self_attn.k_proj,layers.3.self_attn.v_proj,layers.3.self_attn.o_proj,layers.3.mlp.gate_proj,layers.3.mlp.up_proj,layers.3.mlp.down_proj,layers.4.self_attn.q_proj,layers.4.self_attn.k_proj,layers.4.self_attn.v_proj,layers.4.self_attn.o_proj,layers.4.mlp.gate_proj,layers.4.mlp.up_proj,layers.4.mlp.down_proj,layers.5.self_attn.q_proj,layers.5.self_attn.k_proj,layers.5.self_attn.v_proj,layers.5.self_attn.o_proj,layers.5.mlp.gate_proj,layers.5.mlp.up_proj,layers.5.mlp.down_proj
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05

### ddp
ddp_timeout: 180000000
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: codeInstruct
template: mistral
cutoff_len: 512
max_samples: 100000000
overwrite_cache: false
preprocessing_num_workers: 8

### output /gemini/data-2/mix-ckpt-70b/cust/math
output_dir: /gemini/data-2/Customization-7Bs/mistral-lora/SAP/mistral-7B-code-SAP
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
report_to: wandb
run_name: mistral-7B-Code-Cust-lora-SAP # 可选

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true

### eval
val_size: 0.08
per_device_eval_batch_size: 32
eval_strategy: steps
eval_steps: 1000
